# Generated by Django 2.2.5 on 2019-09-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dealer',
            table='dealer',
        ),
    ]
